use sea_orm::{ConnectionTrait, Database, DatabaseConnection, DbErr};

use crate::_common::app_config::AppConfig;
use crate::_common::jwk_cache::JwkCache;

/// アプリ全体で共有する状態。`#[derive(Clone)]` で `axum::Router` に渡す。
#[derive(Clone)]
pub struct AppState {
    pub config: AppConfig,
    pub db: DatabaseConnection,
    /// Google JWK のキャッシュ。起動時に取得（失敗時は空のまま、auth で 500）。
    pub jwk_cache: JwkCache,
}

impl AppState {
    /// DB 接続を確立し、`CREATE TABLE IF NOT EXISTS` を流し、Google JWK を取得する。
    pub async fn new(config: AppConfig) -> Result<Self, DbErr> {
        let db = Database::connect(&config.database_url).await?;
        ensure_schema(&db).await?;

        let jwk_cache = match JwkCache::fetch().await {
            Ok(c) => {
                tracing::info!("Google JWK を取得しました（{} keys）", c.keys.len());
                c
            }
            Err(e) => {
                // 起動失敗にはしない。オフライン開発でも /healthz / Phase 1 動作確認は可能にしておく。
                tracing::warn!(
                    "Google JWK の取得に失敗（auth API は使用不可になります）: {e}"
                );
                JwkCache::default()
            }
        };

        Ok(Self {
            config,
            db,
            jwk_cache,
        })
    }
}

/// 起動時に冪等なスキーマ初期化を行う。マイグレーションツールは使わない方針。
async fn ensure_schema(db: &DatabaseConnection) -> Result<(), DbErr> {
    db.execute_unprepared(
        r#"
        CREATE TABLE IF NOT EXISTS todos (
            id          BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            user_id     BIGINT       NOT NULL DEFAULT 0,
            title       TEXT         NOT NULL,
            completed   BOOLEAN      NOT NULL DEFAULT FALSE,
            created_at  TIMESTAMPTZ  NOT NULL,
            updated_at  TIMESTAMPTZ  NOT NULL
        );

        CREATE TABLE IF NOT EXISTS users (
            id          BIGINT       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            google_sub  TEXT         UNIQUE NOT NULL,
            email       TEXT         NOT NULL,
            name        TEXT         NOT NULL,
            picture     TEXT,
            created_at  TIMESTAMPTZ  NOT NULL
        );

        CREATE INDEX IF NOT EXISTS idx_todos_user_id ON todos(user_id);
        "#,
    )
    .await?;
    Ok(())
}
